export const projects = [
  {
    title: 'SIMS-PPOB',
    description: "A Simple App that use to complete task for Nutech Test",
      // image: '/images/1.png',
      tags: ['Flutter', 'Dio', 'Provider'],
    source: 'https://github.com/mirfan23/sims-ppob',
    // visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"A E-Catalog App that can use to use search Painting (Local)",
    image: '/images/2.png',
    tags: ['Flutter', 'GetX', 'Hive', 'STRAPI'],
    source: 'https://github.com/mirfan23/e-commerce',
    // visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'AI-GPT3',
    description: "A Simple landing page with AI theme",
      image: '/images/3.jpg',
      tags: ['React'],
    source: 'https://github.com/mirfan23/ai-gpt3',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Gerich Restaurant',
    description: "A Simple landing page with Restaurant theme",
    image: '/images/4.jpg',
    tags: ['React'],
    source: 'https://github.com/mirfan23/gericht-restaurant',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Phincon Attendance',
    description: "An app taht use to complete Phincon Test",
    image: '/images/4.jpg',
    tags: ['Kotlin', 'Firebase', 'ViewPager'],
    source: 'https://github.com/mirfan23/PhinconAttendance',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Story App',
    description: "An app that can use to see list of story that stored in database",
    image: '/images/4.jpg',
    tags: ['Kotlin', 'Retorfit', 'Datastore'],
    source: 'https://github.com/mirfan23/storyapp',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'Logbook Mobile',
    description: "An app that use to marking a date that for an activity",
    image: '/images/4.jpg',
    tags: ['Flutter', 'GetX'],
    source: 'https://github.com/mirfan23/gericht-restaurant',
    visit: 'https://google.com',
    id: 6,
  },
  {
    title: 'CRUD-API',
    description: "A Simple simple project that can do CRUD for user",
    image: '/images/4.jpg',
    tags: ['Express', 'MongoDB', 'TypeScript'],
    source: 'https://github.com/mirfan23/gericht-restaurant',
    visit: 'https://google.com',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];